#! /bin/sh
### BEGIN INIT INFO
# Provides:          wifi for wps
# Required-Start:    $
# Required-Stop:
# Default-Start:     
# Default-Stop:
# Short-Description: start wifi service
### END INIT INFO

do_start () {
	echo "start wifi wps......"
	insmod /root/otg-hs.ko
	insmod /root/8188eu.ko
	sleep 2
	wpa_supplicant -Dwext -iwlan0 -c/etc/wpa_supplicant.conf -B
	wpa_cli -iwlan0 wps_pbc any
	dhclient wlan0
	ifconfig

	#dhcpd
}

do_stop () {
	echo "stop wifi wps......"
	killall dhclient
	killall wpa_supplicant
	rmmod 8188eu
	rmmod otg-hs
}

do_restart () {
	echo "restart wifi wps......"
	do_stop
	do_start
}

do_status () {
	echo "status wifi wps......"
}

case "$1" in
  start)
	do_start
	;;
  restart|reload|force-reload)
	do_restart
	;;
  stop)
	do_stop
	;;
  status)
	do_status
	;;
  *)
	echo "Usage: $0 start|stop|restart|status"
	exit 3
	;;
esac

exit 0 
